### ISSUE TITLE
python3-lxa-iobus RDEPENDS on missing python3-aiohttp-json-rpc

### ISSUE THREAD

**Issue by Bastian-Krause** [labgrid-project/meta-labgrid#43]
The `python3-lxa-iobus` recipe RDEPENDS on `python3-aiohttp-json-rpc`, which is neither present in this layer nor in core/meta-python. The recipe resides instead in https://github.com/linux-automation/meta-lxatac/tree/langdale/meta-lxatac-software/recipes-python/python3-aiohttp-json-rpc

Introduced in #17.

**Comment by ejoerns** [comment]
So we should either copy the recipe or remove `python3-lxa-iobus` (and expect `meta-lxatac` to provide it).
